#!/usr/bin/env bash
# claude/install.sh — link the shared Claude Code config into ~/.claude, then generate settings.json.
#
# Five content folders are linked whole, so anything added to, changed in or removed from them in
# this repo takes effect in ~/.claude immediately — no re-run needed:
#
#   ~/.claude/agents    → claude/agents          ~/.claude/hooks   → claude/hooks
#   ~/.claude/commands  → claude/commands        ~/.claude/skills  → claude/skills
#   ~/.claude/rules     → claude/rules           ~/.claude/statusline-command.sh → file link
#   ~/.claude/settings.json                      → generated by scripts/claude-settings
#
# ~/.claude ITSELF is never linked: it is Claude Code's runtime directory (transcripts, prompt
# history, jobs, OAuth-bearing backups, settings.local.json) and must stay out of this public repo.
# The flip side of linking the content folders: anything written INTO them — a skill installed by a
# third-party tool, an agent created with /agents — lands in this repo's working tree. `--status`
# lists such uncommitted items so they are noticed before a `git add`.
#
# Usage: install.sh [--status | --dry-run | --materialize] [--no-settings]
#   --status       report link health, uncommitted items and settings state; exit 1 if unhealthy
#   --dry-run      print what would change
#   --materialize  replace the agents/commands/rules/skills links with real copies (stopgap if a
#                  Claude Code release stops following symlinks); re-run without it to relink
#   --no-settings  skip settings.json generation
#
# Migrating a real folder (e.g. the earlier per-item layout): its entries are checked first. Links
# into this package, identical copies of package items and dangling links into the package are
# safe; a copy that differs from the package is kept in the backup with a warning. Anything else
# (an unmanaged skill, a foreign link) blocks THAT folder, which is left untouched, and is listed.
#
# Idempotent and non-interactive. Replaced folders and links go to
# ~/.claude-migration-backup/<timestamp>/ — never inside ~/.claude, where a backed-up skill would
# load as a duplicate. Written for macOS /bin/bash 3.2.
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
BACKUP_ROOT="${CLAUDE_BACKUP_DIR:-$HOME/.claude-migration-backup}"
FOLDERS="agents commands rules hooks skills"
# hooks stays linked under --materialize: hook scripts are run by the shell, which always follows links
MATERIALIZE_FOLDERS="agents commands rules skills"

MODE=install
SETTINGS=1
for arg in "$@"; do
    case "$arg" in
        --status)      MODE=status ;;
        --dry-run)     MODE=dry-run ;;
        --materialize) MODE=materialize ;;
        --no-settings) SETTINGS=0 ;;
        -h|--help)     sed -n '2,31p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) printf 'install.sh: unknown argument: %s\n' "$arg" >&2; exit 2 ;;
    esac
done

CHANGED=0
PROBLEMS=0
_BACKUP=""

say()  { printf '%s\n' "$*"; }
note() { printf '  %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }

act() {
    # act <description> <command...>: run (or only describe, in dry-run) a change
    local desc="$1"; shift
    CHANGED=$((CHANGED + 1))
    if [ "$MODE" = "dry-run" ]; then
        note "would: $desc"
    else
        note "$desc"
        "$@"
    fi
}

ensure_backup() {
    # Sets $_BACKUP once per run. Call it directly, never inside $(...): a subshell's assignment is
    # lost, so every call would mint a fresh timestamp — splitting one run's backups across folders
    # whenever the clock ticks, and leaving the "backups:" summary unprinted.
    if [ -z "$_BACKUP" ]; then
        _BACKUP="$BACKUP_ROOT/$(date +%Y%m%d_%H%M%S)"
        [ "$MODE" = "dry-run" ] || mkdir -p "$_BACKUP"
    fi
}

move_to_backup() {
    # move_to_backup <path under CLAUDE_DIR>: moves a file, directory or the symlink itself
    local path="$1" dest
    ensure_backup
    dest="$_BACKUP/${path#"$CLAUDE_DIR"/}"
    mkdir -p "$(dirname "$dest")"
    mv "$path" "$dest"
}

replace_with_link() {
    # replace_with_link <src> <dest>: back up whatever is at dest, then link. A directory cannot be
    # atomically swapped for a symlink from the shell; the gap is one rename to one symlink(2).
    local src="$1" dest="$2"
    if [ -e "$dest" ] || [ -L "$dest" ]; then
        move_to_backup "$dest"
    fi
    ln -s "$src" "$dest"
}

same_content() {
    # same_content <a> <b>: identical file or identical directory tree
    if [ -d "$1" ] && [ -d "$2" ]; then
        diff -rq "$1" "$2" >/dev/null 2>&1
    elif [ -f "$1" ] && [ -f "$2" ]; then
        cmp -s "$1" "$2"
    else
        return 1
    fi
}

# classify_folder <folder>: prints "unmanaged <name>" and "differs <name>" lines for a real folder
classify_folder() {
    local dest="$CLAUDE_DIR/$1" src="$PKG_DIR/$1" entry name target
    for entry in "$dest"/* "$dest"/.[!.]*; do
        [ -e "$entry" ] || [ -L "$entry" ] || continue
        name="$(basename "$entry")"
        [ "$name" = ".DS_Store" ] && continue
        if [ -L "$entry" ]; then
            target="$(readlink "$entry")"
            case "$target" in
                "$PKG_DIR"/*) ;;                      # per-item link into this package (live or dangling)
                *) printf 'unmanaged %s\n' "$name" ;; # a link to somewhere else
            esac
        elif [ -e "$src/$name" ]; then
            same_content "$entry" "$src/$name" || printf 'differs %s\n' "$name"
        else
            printf 'unmanaged %s\n' "$name"
        fi
    done
}

install_folder() {
    local folder="$1" src="$PKG_DIR/$1" dest="$CLAUDE_DIR/$1" current report line
    if [ -L "$dest" ]; then
        current="$(readlink "$dest")"
        [ "$current" = "$src" ] && return 0
        act "relink $dest (was → $current; old link backed up)" replace_with_link "$src" "$dest"
    elif [ -d "$dest" ]; then
        report="$(classify_folder "$folder")"
        # capture-then-test: `printf | grep -q` under pipefail can SIGPIPE the producer and invert
        if case "$report" in unmanaged\ *|*"
unmanaged "*) true ;; *) false ;; esac; then
            warn "$dest was NOT linked — it holds items this repo does not manage:"
            printf '%s\n' "$report" | sed -n 's/^unmanaged /      /p' >&2
            warn "move each into $src (to share it) or out of ~/.claude, then re-run install.sh"
            PROBLEMS=$((PROBLEMS + 1))
            return 0
        fi
        printf '%s\n' "$report" | sed -n 's/^differs //p' | while IFS= read -r line; do
            if [ -n "$line" ]; then
                warn "$folder/$line differs from the repo copy; the local version is kept in the backup"
            fi
        done
        act "replace folder $dest with a link (old folder backed up)" replace_with_link "$src" "$dest"
    elif [ -e "$dest" ]; then
        act "replace file $dest with a folder link (backed up)" replace_with_link "$src" "$dest"
    else
        act "link $dest" ln -s "$src" "$dest"
    fi
}

# The single-quoted scripts receive $1/$2/$3 as positional arguments on purpose.
# shellcheck disable=SC2016
install_statusline() {
    local src="$PKG_DIR/statusline-command.sh" dest="$CLAUDE_DIR/statusline-command.sh"
    if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
        return 0
    fi
    if [ -f "$dest" ] && [ ! -L "$dest" ] && ! cmp -s "$src" "$dest"; then
        ensure_backup
        act "back up differing $dest" sh -c 'mkdir -p "$(dirname "$2")" && cp -p "$1" "$2"' _ \
            "$dest" "$_BACKUP/statusline-command.sh"
    fi
    # atomic: rename(2) replaces the file or old link in one step
    act "link $dest" sh -c 'ln -s "$1" "$2" && mv -f "$2" "$3"' _ "$src" "$dest.dotfiles-tmp.$$" "$dest"
}

status_folder() {
    local folder="$1" src="$PKG_DIR/$1" dest="$CLAUDE_DIR/$1" untracked line
    if [ -L "$dest" ]; then
        if [ "$(readlink "$dest")" != "$src" ]; then
            warn "$dest links elsewhere: $(readlink "$dest")"
            PROBLEMS=$((PROBLEMS + 1))
        fi
    elif [ -d "$dest" ]; then
        warn "$dest is a real folder, not a link — new repo items will not appear (run install.sh)"
        PROBLEMS=$((PROBLEMS + 1))
    else
        warn "$dest is missing"
        PROBLEMS=$((PROBLEMS + 1))
    fi
    if git -C "$PKG_DIR" rev-parse --git-dir >/dev/null 2>&1; then
        untracked="$(git -C "$PKG_DIR" status --porcelain --untracked-files=normal -- "$folder" 2>/dev/null | sed -n 's/^?? //p')"
        if [ -n "$untracked" ]; then
            printf '%s\n' "$untracked" | while IFS= read -r line; do
                note "uncommitted: $line — created or installed here; commit it to share it, or remove it (public repo)"
            done
        fi
    fi
}

status_statusline() {
    local src="$PKG_DIR/statusline-command.sh" dest="$CLAUDE_DIR/statusline-command.sh"
    if [ ! -L "$dest" ] || [ "$(readlink "$dest")" != "$src" ]; then
        warn "$dest is not linked to $src"
        PROBLEMS=$((PROBLEMS + 1))
    fi
}

# shellcheck disable=SC2016
materialize_folder() {
    local src="$PKG_DIR/$1" dest="$CLAUDE_DIR/$1"
    [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ] || return 0
    act "materialize $dest (real copy of $src)" sh -c 'rm "$1" && cp -R "$2" "$1"' _ "$dest" "$src"
}

say "Claude Code config: $PKG_DIR → $CLAUDE_DIR ($MODE)"

if [ "$MODE" = "install" ] || [ "$MODE" = "materialize" ]; then
    mkdir -p "$CLAUDE_DIR"
fi

case "$MODE" in
    status)
        for folder in $FOLDERS; do status_folder "$folder"; done
        status_statusline
        ;;
    materialize)
        for folder in $MATERIALIZE_FOLDERS; do materialize_folder "$folder"; done
        ;;
    *)
        for folder in $FOLDERS; do install_folder "$folder"; done
        install_statusline
        ;;
esac

if [ "$SETTINGS" -eq 1 ]; then
    case "$MODE" in
        status)
            "$PKG_DIR/scripts/claude-settings" status | sed 's/^/  /' || PROBLEMS=$((PROBLEMS + 1)) ;;
        dry-run)
            note "would: run claude-settings sync"
            "$PKG_DIR/scripts/claude-settings" status | sed 's/^/  /' || true ;;
        *)
            "$PKG_DIR/scripts/claude-settings" sync | sed 's/^/  /' ;;
    esac
fi

if [ "$MODE" = "status" ]; then
    if [ "$PROBLEMS" -eq 0 ]; then say "healthy"; else say "$PROBLEMS problem(s)"; exit 1; fi
else
    say "changed: $CHANGED"
    [ -z "$_BACKUP" ] || [ "$MODE" = "dry-run" ] || say "backups: $_BACKUP"
    if [ "$PROBLEMS" -gt 0 ]; then
        say "$PROBLEMS folder(s) left unlinked — see above"
        exit 1
    fi
fi
