#!/usr/bin/env bash
# claude/install.sh — link the shared Claude Code config into ~/.claude, then generate settings.json.
#
# ~/.claude is Claude Code's live runtime directory (transcripts, history, jobs, OAuth-bearing
# backups). It is NEVER linked as a whole. Each managed item is linked individually, so
# ~/.claude/{agents,commands,rules,hooks,skills} stay real directories owned by the runtime and
# anything Claude or a third-party installer creates there stays out of this public repo:
#
#   agents/*.md  commands/*.md  rules/*.md  hooks/*   → file symlinks
#   skills/<name>/                                    → directory symlinks
#   statusline-command.sh                             → file symlink
#   settings.json                                     → generated by scripts/claude-settings
#
# Usage: install.sh [--status | --dry-run | --materialize] [--no-settings]
#   --status       report link health and settings state; change nothing; exit 1 if unhealthy
#   --dry-run      print what would change
#   --materialize  replace every managed symlink with a real copy (stopgap if a Claude Code
#                  release stops following symlinks); re-run without it to relink
#   --no-settings  skip settings.json generation
#
# Idempotent and non-interactive. Backups go to ~/.claude-migration-backup/<timestamp>/ —
# never inside ~/.claude, where a backed-up skill directory would load as a duplicate skill.
# Written for macOS /bin/bash 3.2.
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
BACKUP_ROOT="${CLAUDE_BACKUP_DIR:-$HOME/.claude-migration-backup}"

MODE=install
SETTINGS=1
for arg in "$@"; do
    case "$arg" in
        --status)      MODE=status ;;
        --dry-run)     MODE=dry-run ;;
        --materialize) MODE=materialize ;;
        --no-settings) SETTINGS=0 ;;
        -h|--help)     sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) printf 'install.sh: unknown argument: %s\n' "$arg" >&2; exit 2 ;;
    esac
done

CHANGED=0
PROBLEMS=0
_BACKUP=""

say()  { printf '%s\n' "$*"; }
note() { printf '  %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }

act() {
    # act <description> <command...>: run (or only describe, in dry-run) a change
    local desc="$1"; shift
    CHANGED=$((CHANGED + 1))
    if [ "$MODE" = "dry-run" ]; then
        note "would: $desc"
    else
        note "$desc"
        "$@"
    fi
}

backup_dir() {
    if [ -z "$_BACKUP" ]; then
        _BACKUP="$BACKUP_ROOT/$(date +%Y%m%d_%H%M%S)"
        [ "$MODE" = "dry-run" ] || mkdir -p "$_BACKUP"
    fi
    printf '%s' "$_BACKUP"
}

move_to_backup() {
    # move_to_backup <path under CLAUDE_DIR>
    local path="$1" rel dest
    rel="${path#"$CLAUDE_DIR"/}"
    dest="$(backup_dir)/$rel"
    mkdir -p "$(dirname "$dest")"
    mv "$path" "$dest"
}

copy_to_backup() {
    # copy_to_backup <file under CLAUDE_DIR>: keep the original in place so the atomic link
    # rename that follows leaves no window where the item is missing
    local path="$1" dest
    dest="$(backup_dir)/${path#"$CLAUDE_DIR"/}"
    mkdir -p "$(dirname "$dest")"
    cp -p "$path" "$dest"
}

# Managed items as "<source>\t<destination>" lines.
managed_items() {
    local kind f name
    for kind in agents commands rules; do
        for f in "$PKG_DIR/$kind"/*.md; do
            [ -f "$f" ] || continue
            printf '%s\t%s\n' "$f" "$CLAUDE_DIR/$kind/$(basename "$f")"
        done
    done
    for f in "$PKG_DIR/hooks"/*; do
        [ -f "$f" ] || continue
        printf '%s\t%s\n' "$f" "$CLAUDE_DIR/hooks/$(basename "$f")"
    done
    for f in "$PKG_DIR/skills"/*/; do
        [ -d "$f" ] || continue
        name="$(basename "$f")"
        printf '%s\t%s\n' "$PKG_DIR/skills/$name" "$CLAUDE_DIR/skills/$name"
    done
    printf '%s\t%s\n' "$PKG_DIR/statusline-command.sh" "$CLAUDE_DIR/statusline-command.sh"
}

link_file() {
    # Atomic: build the link beside the destination, then rename over it. rename(2) replaces a
    # symlink or regular file in one step, so a running session never sees the item missing.
    local src="$1" dest="$2" tmp
    tmp="$dest.dotfiles-tmp.$$"
    ln -s "$src" "$tmp"
    mv -f "$tmp" "$dest"
}

link_dir() {
    # A real directory at dest must be moved out first: `ln -sfn src dest` onto a real directory
    # creates dest/<basename> INSIDE it instead of replacing it.
    local src="$1" dest="$2"
    ln -sfn "$src" "$dest"
}

install_item() {
    local src="$1" dest="$2" current
    if [ -L "$dest" ]; then
        current="$(readlink "$dest")"
        [ "$current" = "$src" ] && return 0
        if [ -d "$src" ]; then
            act "relink $dest (was → $current)" link_dir "$src" "$dest"
        else
            act "relink $dest (was → $current)" link_file "$src" "$dest"
        fi
    elif [ -d "$dest" ]; then
        act "back up real directory $dest and link it" move_to_backup "$dest"
        [ "$MODE" = "dry-run" ] || link_dir "$src" "$dest"
    elif [ -e "$dest" ]; then
        if [ -d "$src" ]; then
            act "back up $dest and link it" move_to_backup "$dest"
            [ "$MODE" = "dry-run" ] || link_dir "$src" "$dest"
        else
            if ! cmp -s "$src" "$dest"; then
                act "back up differing file $dest" copy_to_backup "$dest"
            fi
            act "replace file $dest with a link" link_file "$src" "$dest"
        fi
    else
        if [ -d "$src" ]; then
            act "link $dest" link_dir "$src" "$dest"
        else
            act "link $dest" link_file "$src" "$dest"
        fi
    fi
}

# The single-quoted scripts receive $1/$2 as positional arguments on purpose.
# shellcheck disable=SC2016
materialize_item() {
    local src="$1" dest="$2"
    [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ] || return 0
    if [ -d "$src" ]; then
        act "materialize $dest" sh -c 'rm "$1" && cp -R "$2" "$1"' _ "$dest" "$src"
    else
        act "materialize $dest" sh -c 'cp -p "$2" "$1.dotfiles-tmp" && mv -f "$1.dotfiles-tmp" "$1"' _ "$dest" "$src"
    fi
}

status_item() {
    local src="$1" dest="$2"
    if [ -L "$dest" ]; then
        if [ "$(readlink "$dest")" != "$src" ]; then
            warn "$dest links elsewhere: $(readlink "$dest")"
            PROBLEMS=$((PROBLEMS + 1))
        fi
    elif [ -e "$dest" ]; then
        # e.g. a third-party installer re-ran and replaced the link with a real copy
        warn "$dest is a real $( [ -d "$dest" ] && echo directory || echo file ), not a link — managed content is shadowed"
        PROBLEMS=$((PROBLEMS + 1))
    else
        warn "$dest is missing"
        PROBLEMS=$((PROBLEMS + 1))
    fi
}

prune_dangling() {
    # Remove symlinks that point into this package at something that no longer exists.
    # Links pointing anywhere else are not ours and are never touched.
    local dir link target
    for dir in agents commands rules hooks skills; do
        [ -d "$CLAUDE_DIR/$dir" ] || continue
        for link in "$CLAUDE_DIR/$dir"/* "$CLAUDE_DIR/$dir"/.[!.]*; do
            [ -L "$link" ] || continue
            target="$(readlink "$link")"
            case "$target" in
                "$PKG_DIR"/*)
                    if [ ! -e "$link" ]; then
                        if [ "$MODE" = "status" ]; then
                            warn "$link is dangling (→ $target)"
                            PROBLEMS=$((PROBLEMS + 1))
                        else
                            act "prune dangling $link" rm "$link"
                        fi
                    fi
                    ;;
            esac
        done
    done
}

say "Claude Code config: $PKG_DIR → $CLAUDE_DIR ($MODE)"

if [ "$MODE" != "status" ]; then
    for sub in agents commands rules hooks skills; do
        if [ -L "$CLAUDE_DIR/$sub" ]; then
            printf 'install.sh: %s is a symlink; per-item linking needs a real directory there. Remove the link and re-run.\n' "$CLAUDE_DIR/$sub" >&2
            exit 1
        fi
        if [ ! -d "$CLAUDE_DIR/$sub" ]; then
            act "create $CLAUDE_DIR/$sub" mkdir -p "$CLAUDE_DIR/$sub"
        fi
    done
fi

while IFS="$(printf '\t')" read -r src dest; do
    [ -n "$src" ] || continue
    case "$MODE" in
        status)      status_item "$src" "$dest" ;;
        materialize) materialize_item "$src" "$dest" ;;
        *)           install_item "$src" "$dest" ;;
    esac
done <<EOF
$(managed_items)
EOF

[ "$MODE" = "materialize" ] || prune_dangling

if [ "$SETTINGS" -eq 1 ]; then
    case "$MODE" in
        status)
            "$PKG_DIR/scripts/claude-settings" status | sed 's/^/  /' || PROBLEMS=$((PROBLEMS + 1)) ;;
        dry-run)
            note "would: run claude-settings sync"
            "$PKG_DIR/scripts/claude-settings" status | sed 's/^/  /' || true ;;
        *)
            "$PKG_DIR/scripts/claude-settings" sync | sed 's/^/  /' ;;
    esac
fi

if [ "$MODE" = "status" ]; then
    if [ "$PROBLEMS" -eq 0 ]; then say "healthy"; else say "$PROBLEMS problem(s)"; exit 1; fi
else
    say "changed: $CHANGED"
    [ -z "$_BACKUP" ] || [ "$MODE" = "dry-run" ] || say "backups: $_BACKUP"
fi
