#!/usr/bin/env zsh

# Install VS Code extensions from extensions.txt
# This script is auto-generated by sync-vscode.sh

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXTENSIONS_FILE="$SCRIPT_DIR/extensions.txt"

if [[ ! -f "$EXTENSIONS_FILE" ]]; then
    echo "Error: extensions.txt not found"
    exit 1
fi

if ! command -v code &> /dev/null; then
    echo "Error: VS Code CLI 'code' command not found"
    exit 1
fi

echo "Installing VS Code extensions..."
while IFS= read -r extension; do
    if [[ -n "$extension" ]]; then
        echo "Installing: $extension"
        code --install-extension "$extension" --force
    fi
done < "$EXTENSIONS_FILE"

echo "✓ Extension installation complete"
